AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  backend

  Sample SAM Template for backend
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: FinanceTrackerUserPool
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
      Schema:
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: false
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: FinanceTrackerWebClient
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
  CommonLayer:
      Type: AWS::Serverless::LayerVersion
      Properties:
        LayerName: CommonLayer
        ContentUri: layers/ft-common-layer
        CompatibleRuntimes:
          - nodejs22.x
  DDBSingleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SingleTable
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: LSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      LocalSecondaryIndexes:
        - IndexName: LSI1
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: LSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST # On-demand billing (no need to set RCU/WCU)
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration:
        Type: REGIONAL
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false
  ExpensesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-functions/functions
      Handler: expenses.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /expenses
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        GetExpenses:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /expenses
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        DeleteExpense:
          Type: Api
          Properties:
            Path: /expenses
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
        PutExpense:
          Type: Api
          Properties:
            Path: /expenses
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        ExpensesOptions:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /expenses
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - expenses.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
  FundSourcesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-functions/functions
      Handler: fund-sources.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        GetFundSources:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fund-sources
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostFundSources:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fund-sources
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        PatchFundSources:
          Type: Api
          Properties:
            Path: /fund-sources/{name}
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        DeleteFundSources:
          Type: Api
          Properties:
            Path: /fund-sources/{name}
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
        FundSourcesOptions:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /fund-sources
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        FundSourcesPathOptions:
          Type: Api
          Properties:
            Path: /fund-sources/{name}
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - fund-sources.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
  TagsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda-functions/functions
      Handler: tags.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        GetTags:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tags
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostTag:
          Type: Api
          Properties:
            Path: /tags
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        PatchTag:
          Type: Api
          Properties:
            Path: /tags/{name}
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        DeleteTag:
          Type: Api
          Properties:
            Path: /tags/{name}
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
        TagsOptions:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /tags
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        TagsPathOptions:
          Type: Api
          Properties:
            Path: /tags/{name}
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - tags.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
  IncomesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/functions
      Handler: incomes.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        GetIncomes:
          Type: Api
          Properties:
            Path: /incomes
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostIncome:
          Type: Api
          Properties:
            Path: /incomes
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        PatchIncome:
          Type: Api
          Properties:
            Path: /incomes
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        DeleteIncome:
          Type: Api
          Properties:
            Path: /incomes
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
        IncomesOptions:
          Type: Api
          Properties:
            Path: /incomes
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - incomes.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
  LendingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/functions
      Handler: lendings.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        GetLendings:
          Type: Api
          Properties:
            Path: /lendings
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostLending:
          Type: Api
          Properties:
            Path: /lendings
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        PatchLending:
          Type: Api
          Properties:
            Path: /lendings
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        DeleteLending:
          Type: Api
          Properties:
            Path: /lendings
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
        LendingsOptions:
          Type: Api
          Properties:
            Path: /lendings
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        GetLendingPayments:
          Type: Api
          Properties:
            Path: /lendings/payments
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostLendingPayment:
          Type: Api
          Properties:
            Path: /lendings/payments
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        LendingPaymentsOptions:
          Type: Api
          Properties:
            Path: /lendings/payments
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - lendings.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
  RecurringExpensesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/functions
      Handler: recurring-expenses.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        GetRecurring:
          Type: Api
          Properties:
            Path: /recurring-expenses
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostRecurring:
          Type: Api
          Properties:
            Path: /recurring-expenses
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        RecurringOptions:
          Type: Api
          Properties:
            Path: /recurring-expenses
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        PatchRecurring:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        DeleteRecurring:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}
            Method: delete
            RestApiId:
              Ref: ApiGatewayApi
        RecurringNameOptions:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        PostRecurringPay:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}/pay
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        RecurringPayOptions:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}/pay
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        GetRecurringPayments:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}/payments
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        RecurringPaymentsOptions:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}/payments
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
        PatchRecurringStatus:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}/status
            Method: patch
            RestApiId:
              Ref: ApiGatewayApi
        RecurringStatusOptions:
          Type: Api
          Properties:
            Path: /recurring-expenses/{name}/status
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - recurring-expenses.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
  TransfersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda-functions/functions
      Handler: transfers.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Layers:
        - !Ref CommonLayer
      Environment:
        Variables:
          DDB_TABLE_NAME: !Ref DDBSingleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DDBSingleTable
      Events:
        GetTransfers:
          Type: Api
          Properties:
            Path: /transfers
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
        PostTransfer:
          Type: Api
          Properties:
            Path: /transfers
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
        TransfersOptions:
          Type: Api
          Properties:
            Path: /transfers
            Method: options
            RestApiId:
              Ref: ApiGatewayApi
            Auth:
              Authorizer: NONE
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - transfers.ts
        External:
          - '@aws-sdk/lib-dynamodb'
          - '@aws-sdk/client-dynamodb'
          - 'ft-common-layer'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ExpensesFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ExpensesFunction.Arn
  ExpensesFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ExpensesFunctionRole.Arn
  DDBSingleTableName:
    Description: DynamoDB table name
    Value: !Ref DDBSingleTable
  DDBSingleTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt DDBSingleTable.Arn
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient